# apiVersion: dapr.io/v1alpha1
# kind: Component
# metadata:
#   name: actorpubsub
#   namespace: actor-clusters
# spec:
#   type: pubsub.redis
#   version: v1
#   metadata:
#   - name: redisHost
#     value: localhost:6379
#   - name: redisPassword
#     value: ""


apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: actorpubsub
  namespace: actor-clusters
spec:
  type: pubsub.azure.servicebus.topics
  version: v1
  metadata:
  # Required when not using Microsoft Entra ID Authentication
  - name: connectionString
    value: "<SERVICE_BUS_ENDPOINT>"
scopes:
  - worker-client